name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: twitter_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Start services
      run: docker-compose up -d

    - name: Wait for DB
      run: |
        sleep 10

    - name: Migrate database
      run: docker-compose exec web python manage.py migrate

    - name: Run tests
      run: docker-compose exec web python manage.py test twitter
